# coding: utf-8

"""
    SWAIN API

    A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dynamic_api import DynamicApi


class TestDynamicApi(unittest.TestCase):
    """DynamicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DynamicApi()

    def tearDown(self) -> None:
        pass

    def test_model_count_post(self) -> None:
        """Test case for model_count_post

        Count entities by filter
        """
        pass

    def test_model_filter_post(self) -> None:
        """Test case for model_filter_post

        Filter entities
        """
        pass

    def test_model_get(self) -> None:
        """Test case for model_get

        List entities
        """
        pass

    def test_model_id_delete(self) -> None:
        """Test case for model_id_delete

        Delete an entity
        """
        pass

    def test_model_id_get(self) -> None:
        """Test case for model_id_get

        Get an entity by ID
        """
        pass

    def test_model_id_put(self) -> None:
        """Test case for model_id_put

        Update an entity
        """
        pass

    def test_model_post(self) -> None:
        """Test case for model_post

        Create a new entity
        """
        pass


if __name__ == '__main__':
    unittest.main()
