# coding: utf-8

"""
    SWAIN API

    A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bulk_operations_api import BulkOperationsApi


class TestBulkOperationsApi(unittest.TestCase):
    """BulkOperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BulkOperationsApi()

    def tearDown(self) -> None:
        pass

    def test_model_filter_delete(self) -> None:
        """Test case for model_filter_delete

        Mass delete entities by filter
        """
        pass

    def test_model_filter_put(self) -> None:
        """Test case for model_filter_put

        Mass update entities by filter
        """
        pass


if __name__ == '__main__':
    unittest.main()
