# coding: utf-8

# flake8: noqa
"""
    SWAIN API

    A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.api_error_response import ApiErrorResponse
from openapi_client.models.api_field_schema import ApiFieldSchema
from openapi_client.models.api_filter_payload import ApiFilterPayload
from openapi_client.models.api_model_schema import ApiModelSchema
from openapi_client.models.api_models_response import ApiModelsResponse
from openapi_client.models.api_relationship_schema import ApiRelationshipSchema
from openapi_client.models.api_success_response import ApiSuccessResponse
from openapi_client.models.api_update_filter_payload import ApiUpdateFilterPayload
from openapi_client.models.auth_auth_result import AuthAuthResult
from openapi_client.models.auth_login_request import AuthLoginRequest
from openapi_client.models.github_com_takifouhal_crudsql_pkg_internal_auth_models_permission import GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission
from openapi_client.models.github_com_takifouhal_crudsql_pkg_internal_auth_models_role import GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
from openapi_client.models.github_com_takifouhal_crudsql_pkg_internal_auth_models_user import GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
from openapi_client.models.query_aggregate_function_spec import QueryAggregateFunctionSpec
from openapi_client.models.query_aggregation_spec import QueryAggregationSpec
from openapi_client.models.query_filter import QueryFilter
from openapi_client.models.query_filter_response import QueryFilterResponse
from openapi_client.models.query_sort_spec import QuerySortSpec
